// <auto-generated />
namespace SalaryArea3._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Salaryyearadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Salaryyearadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201710281355163_Salaryyearadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
